version: 2
registries:
  npm-registry-npm-pkg-github-com-goproperly:
    type: npm-registry
    url: https://npm.pkg.github.com/goproperly
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_GOPROPERLY_TOKEN}}"
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    timezone: America/New_York
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: semantic-release
    versions:
    - 17.3.7
  - dependency-name: husky
    versions:
    - 4.3.8
  - dependency-name: rollup
    versions:
    - 2.35.1
    - 2.38.3
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.11.1
    - 4.14.1
  - dependency-name: eslint
    versions:
    - 7.19.0
  - dependency-name: "@goproperly/eslint-config-properly-base"
    versions:
    - 1.2.16
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.11.1
    - 4.14.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: tslib
    versions:
    - 2.0.3
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.7
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  registries:
  - npm-registry-npm-pkg-github-com-goproperly
  - npm-registry-npm-pkg-github-com
